/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"
#include <stdbool.h>

bool_t *
isprime_1_svc(input *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	printf("Called server with arg %d\n", argp->num);
	bool isPrime = true;
	int num = argp->num;
	if(num == 1) isPrime = false;
	for(int i = 2; i * i <= num; i++) {
		if(num % i == 0) {
			isPrime = false;
		}
	}
	result = isPrime;
	return &result;
}
