/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"


void
prime_prog_1(char *host, int num)
{
	CLIENT *clnt;
	bool_t  *result_1;
	input  isprime_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PRIME_PROG, PRIME_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	isprime_1_arg.num = num;
	result_1 = isprime_1(&isprime_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		if(*result_1) {
			printf("The number %d is prime\n", num);
		} else {
			printf("The number %d is NOT prime\n", num);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Please enter number: \n");
	int num;
	scanf("%d",&num);
	prime_prog_1 (host, num);
exit (0);
}
