/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cmp.h"
#include<stdlib.h>
#include<string.h>

int *
cmp_1_svc(input *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("strings received of size %d %d \n", argp->n1, argp->n2);


	int n1 = argp->n1, n2 = argp->n2;

	char *s1 = (char *)malloc(n1 * sizeof(char *));
	char *s2 = (char *)malloc(n2 * sizeof(char *));

	for(int i = 0; i < n1; i++) {
		s1[i] = argp->s1[i];
	}

	for(int i = 0; i < n2; i++) {
		s2[i] = argp->s2[i];
	}

	printf("%s %s \n", s1 , s2);

	int ans = 0;
	for(int i = 0; i + n2 - 1 < n1; i++) {
		int f = 1;

		for(int j = 0; j < n2; j++) {
			if(s1[i+j] == s2[j] ) continue;
			f = 0;
			break;
		}

		if(f) {
			ans = 1;
			break;
		}
	}

	result = ans;
	return &result;
}
