/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 
#include "pal.h"
 
int *
pal_1_svc(input *argp, struct svc_req *rqstp)
{
    static int  result;
 
    /*
     * insert server code here
     */
 

	int n = argp->n;

 
    printf("Received input in server of size %d\n", n);
 
    int ans = 1;
 
    for(int i = 0; i < n; i++) {
        if(argp->s[i] != argp->s[n - 1 - i]) {
            ans = 0;
            break;
        }  
    }
 

    result = ans;
    return &result;
}
