/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 
#include "pal.h"
 
 
void
pal_prog_1(char *host, int n, char *s)
{
    CLIENT *clnt;
    int  *result_1;
    input  pal_1_arg;
 
#ifndef DEBUG
    clnt = clnt_create (host, PAL_PROG, PAL_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif  /* DEBUG */
 
	pal_1_arg.n = n;
	for(int i = 0; i < n; i++) {
		pal_1_arg.s[i] = s[i];
	}

    result_1 = pal_1(&pal_1_arg, clnt);
    if (result_1 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    } else {
        if(*result_1) {
            printf("String is a palindrome \n");
        } else {
            printf("String is not a palindrom \n");
        }
    }
#ifndef DEBUG
    clnt_destroy (clnt);
#endif   /* DEBUG */
}


 
 
int
main (int argc, char *argv[])
{
    char *host;
 
    if (argc < 2) {
        printf ("usage: %s server_host\n", argv[0]);
        exit (1);
    }
    host = argv[1];
 
	int n;
	printf("Enter the size of string\n");
	scanf("%d",&n);

    char s[100];
    printf("Enter string: \n");
    scanf("%s", &s);
 
    pal_prog_1 (host, n, s);
}