/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

float *
add_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	printf("Called server add with args (%f,%f)\n", argp->num1, argp->num2);

	result = argp->num1 + argp->num2;

	return &result;
}

float *
sub_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	printf("Called server subtract with args (%f,%f)\n", argp->num1, argp->num2);

	result = argp->num1 - argp->num2;

	return &result;
}

float *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("Called server multiply with args (%f,%f)\n", argp->num1, argp->num2);

	result = argp->num1 * argp->num2;

	return &result;
}

float *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("Called server divide with args (%f,%f)\n", argp->num1, argp->num2);

	result = argp->num1 / argp->num2;

	return &result;
}
