/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"


void
calculate_prog_1(char *host, int num1, int num2, char op)
{
	CLIENT *clnt;
	float  *result_1;
	inputs  add_1_arg;
	float  *result_2;
	inputs  sub_1_arg;
	float  *result_3;
	inputs  mul_1_arg;
	float  *result_4;
	inputs  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATE_PROG, CALCULATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(op == '+') {
		add_1_arg.num1=num1;
		add_1_arg.num2=num2;
		add_1_arg.op = op;
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		} 
		else {
			printf("Result : %f \n", *result_1);
		}
	}
	else if(op == '-') {
		sub_1_arg.num1=num1;
		sub_1_arg.num2=num2;
		sub_1_arg.op = op;
		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("Result : %f \n", *result_2);
		}
	}
	else if(op == '*') {
		mul_1_arg.num1=num1;
		mul_1_arg.num2=num2;
		mul_1_arg.op = op;
		result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("Result : %f \n", *result_3);
		}
	}
	else {
		div_1_arg.num1=num1;
		div_1_arg.num2=num2;
		div_1_arg.op = op;
		if(num2 == 0) {
			printf("Divison by 0 not allowed\n");
			exit(0);
		}
		result_4 = div_1(&div_1_arg, clnt);
		if (result_4 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("Result : %f \n", *result_4);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	float a, b;
	char op;
	printf("Enter Num1: \n");
	scanf("%f",&a);
	printf("Enter Num2: \n");
	scanf("%f",&b);
	printf("Enter Operator(+,-,*,/)\n");
	scanf("%s",&op);

	calculate_prog_1 (host, a, b, op);
exit (0);
}
