/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include<string.h>
#include "cmp.h"

int *
cmp_1_svc(input *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("strings received of size %d %d", argp->n1, argp->n2);

	printf("%s %s\n", argp->s1, argp->s2);

	int n1 = argp->n1, n2 = argp->n2;

	int l = n1;
	if(n1 > n2) l = n2;
	char s1[50], s2[50];
	
	result = strcmp(argp->s1, argp->s2);
	return &result;
}
