/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIB_H_RPCGEN
#define _FIB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int num;
};
typedef struct input input;

#define FIB_PROG 0x12345678
#define FIB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define fib 1
extern  char ** fib_1(input *, CLIENT *);
extern  char ** fib_1_svc(input *, struct svc_req *);
extern int fib_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fib 1
extern  char ** fib_1();
extern  char ** fib_1_svc();
extern int fib_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIB_H_RPCGEN */
