/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"


void
fib_prog_1(char *host, int n)
{
	CLIENT *clnt;
	char * *result_1;
	input  fib_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIB_PROG, FIB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	fib_1_arg.num=n;
	result_1 = fib_1(&fib_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		if(n == 0) {
			printf("enter number >= 1\n");
			exit(0);
		}
		printf("Result : \n");
		printf("%s\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int n;
	printf("Enter number \n");
	scanf("%d", &n);
	fib_prog_1 (host,n);
exit (0);
}
