/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"

char **
fib_1_svc(input *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	printf("Called server with arg %d\n", argp->num);
	int num = argp->num;
	if(num == 1) {
		result = "1";
	} else if(num == 2) {
		result = "1 1";
	} else {
		int t1 = 0, t2 = 1;
		int next = 1;
		int a[num+1];
		a[0] = 0, a[1] = 1, a[2] = 1;
		char str[10000];
		int index = 0;
		for (int i=3; i<=num; i++) {
			a[i] = a[i-1] + a[i-2];
		}
		for(int i = 1; i <= num; i++) {
			index += sprintf(&str[index], "%d ", a[i]);
		}
		result = str;
	}
	return &result;
}
