/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "leap.h"

int *
leap_1_svc(input *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	printf("Server received input %d\n", argp->year);

	int year = argp->year;

	if (year % 400 == 0) {
	  result = 1;
   }
   else if (year % 100 == 0) {
	  result = 0;
   }
   else if (year % 4 == 0) {
	  result = 1;
   }
   else {
	  result = 0;
   }

	return &result;
}
