/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result = 1;

	/*
	 * insert server code here
	 */

	printf("fact called with args %d \n", argp->n);

	int num = argp->n, ans = 1;

	for(int i = 1; i <= num; i++) {
		ans *= i;
	}

	result = ans;

	return &result;
}
