CREATE TABLE TGIAIEA (MBR_ID VARCHAR(100) NOT NULL, ENV_CD VARCHAR(100) NOT NULL,STAT_CD VARCHAR(100) NOT NULL, ENDPNT_URL_ADDR VARCHAR(100) NOT NULL, CAAS_KEY_ALIAS_TXT INT NOT NULL,ENDPNT_URL_DESC VARCHAR(100) NOT NULL, UPDT_TS VARCHAR(100) NOT NULL, MOD_CD VARCHAR(100) NOT NULL);
ALTER TABLE TGIAIEA ADD PRIMARY KEY(MBR_ID,ENV_CD,MOD_CD);

-- CREATE TABLE TGIAIEA1 (MBR_ID VARCHAR(100) NOT NULL, ENV_CD VARCHAR(100) NOT NULL,STAT_CD VARCHAR(100) NOT NULL, ENDPNT_URL_ADDR VARCHAR(100) NOT NULL, CAAS_KEY_ALIAS_TXT VARCHAR(100) NOT NULL,ENDPNT_URL_DESC VARCHAR(100) NOT NULL, UPDT_TS VARCHAR(100) NOT NULL, MOD_CD VARCHAR(100) NOT NULL);
-- ALTER TABLE TGIAIEA1 ADD PRIMARY KEY(MBR_ID,ENV_CD,MOD_CD);

-- uncomment at time of testing 
CREATE TABLE TEST (ID VARCHAR(10) NOT NULL, NAME VARCHAR(100),EMAIL VARCHAR(100) NOT NULL);
ALTER TABLE TEST ADD PRIMARY KEY(ID);

CREATE TABLE TEST1 (ID VARCHAR(10) NOT NULL, NAME VARCHAR(100),EMAIL VARCHAR(100) NOT NULL,SCORE DECIMAL(3,1) NOT NULL,MARKS NUMERIC(3,1) NOT NULL);
ALTER TABLE TEST1 ADD PRIMARY KEY(ID);