/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "stats.h"

output *
stats_1_svc(input *argp, struct svc_req *rqstp)
{
	static output  result;

	/*
	 * insert server code here
	 */

	int n = argp->n;
	int *arr = argp->arr;

	printf("Received array of size %d\n", n);

	int mx = arr[0], mn = arr[0];
	float avg = arr[0];

	for(int i = 0; i < n; i++) {
		if(arr[i] > mx) mx = arr[i];
		if(arr[i] < mn) mn = arr[i];
		avg += arr[i];
	}
	avg /= n;

	result.mx = mx;
	result.mn = mn;
	result.avg = avg;
	return &result;
}
