/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "swap.h"

output *
swap_1_svc(input *argp, struct svc_req *rqstp)
{
	static output  result;

	/*
	 * insert server code here
	 */
	int a= argp->a, b = argp->b;
	a=a+b;//a=30 (10+20)
	b=a-b;//b=10 (30-20)
	a=a-b;//a=20 (30-10)

	result.a = a;
	result.b = b;
	
	return &result;
}
