/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "swap.h"


void
swap_prog_1(char *host,int a, int b)
{
	CLIENT *clnt;
	output  *result_1;
	input  swap_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SWAP_PROG, SWAP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	swap_1_arg.a = a, swap_1_arg.b = b;
	result_1 = swap_1(&swap_1_arg, clnt);
	if (result_1 == (output *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("After swapping \n");
		printf("a = %d\n", result_1->a);
		printf("b = %d\n", result_1->b);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int a, b;
	printf("Enter two numbers to swap \n");
	scanf("%d %d", &a, &b);
	swap_prog_1 (host,a,b);

exit (0);
}
