/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cmp.h"


void
cmp_prog_1(char *host, int n, int *a)
{
	CLIENT *clnt;
	output  *result_1;
	input  cmp_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CMP_PROG, CMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	cmp_1_arg.n = n;
	for(int i = 0; i < n; i++) {
		cmp_1_arg.a[i] = a[i];
	}
	result_1 = cmp_1(&cmp_1_arg, clnt);
	if (result_1 == (output *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Reversed array: \n");
		for(int i = 0; i < n; i++) {
			printf("%d ", result_1->a[i]);
		}
		printf("\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int n;
	printf("Enter the number of elements \n");
	scanf("%d", &n);
	int a[100];
	printf("Enter %d elements", n);
	for(int i = 0; i < n; i++) {
		scanf("%d",&a[i]);
	}
	cmp_prog_1 (host,n,a);
exit (0);
}
