/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sqroot.h"


void
sqroot_prog_1(char *host, float n)
{
	CLIENT *clnt;
	float  *result_1;
	input  sqroot_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQROOT_PROG, SQROOT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	sqroot_1_arg.a = n;
	result_1 = sqroot_1(&sqroot_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("The square root of %f is %f \n", n, *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	float num;
	printf("Enter the number: \n");
	scanf("%f", &num);

	sqroot_prog_1 (host,num);
exit (0);
}
