/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <math.h>
#include "sqroot.h"

float *
sqroot_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	float n = argp->a;
	printf("Received input number %f\n", n);

	result = sqrt(n);
	return &result;
}
