/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cmp.h"


void
cmp_prog_1(char *host, int n1, int n2, char *s1, char *s2)
{
	CLIENT *clnt;
	output  *result_1;
	input  cmp_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CMP_PROG, CMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	cmp_1_arg.n1 = n1;
	cmp_1_arg.n2 = n2;

	for(int i = 0; i < n1; i++) {
		cmp_1_arg.s1[i] = s1[i];
	}

	for(int i = 0; i < n2; i++) {
		cmp_1_arg.s2[i] = s2[i];
	}

	result_1 = cmp_1(&cmp_1_arg, clnt);
	if (result_1 == (output *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Combined string %s \n", result_1->s);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	int n1, n2;
	char s1[50], s2[50];

	printf("Enter the size of string 1\n");
	scanf("%d", &n1);

	printf("Enter the size of string 2 \n");
	scanf("%d", &n2);

	printf("Enter string 1\n");
	scanf("%s", s1);
	printf("Enter string 1\n");
	scanf("%s", s2);

	cmp_prog_1 (host, n1, n2, s1, s2);	
exit (0);
}
