/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cmp.h"

output *
cmp_1_svc(input *argp, struct svc_req *rqstp)
{
	static output  result;

	/*
	 * insert server code here
	 */

		printf("strings received of size %d %d \n", argp->n1, argp->n2);


	int n1 = argp->n1, n2 = argp->n2;

	for(int i = 0; i < n1 + n2; i++) {
		if(i >= n1) result.s[i] = argp->s2[i - n1];
		else result.s[i] = argp->s1[i];
	}

	return &result;
}
