/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GCD_H_RPCGEN
#define _GCD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int a;
	int b;
};
typedef struct input input;

#define GCD_PROG 0x12345678
#define GCD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define gcd 1
extern  int * gcd_1(input *, CLIENT *);
extern  int * gcd_1_svc(input *, struct svc_req *);
extern int gcd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define gcd 1
extern  int * gcd_1();
extern  int * gcd_1_svc();
extern int gcd_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GCD_H_RPCGEN */
