/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gcd.h"


void
gcd_prog_1(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	input  gcd_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GCD_PROG, GCD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	gcd_1_arg.a = a;
	gcd_1_arg.b = b;

	result_1 = gcd_1(&gcd_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Result GCD = %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int a, b;

	printf("Enter number 1: \n");
	scanf("%d", &a);

	printf("Enter number 2: \n");
	scanf("%d", &b);

	gcd_prog_1 (host, a, b);
exit (0);
}
