/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gcd.h"

int *
gcd_1_svc(input *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int a = argp->a, b = argp->b;
	printf("Received input (%d,%d)", a, b);

	int g = 1;

	for(int i = 1; i <= a; i++) {
		if(a % i == 0 && b % i == 0) g = i;
	}

	result = g;
	return &result;
}
