/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 
#include "max.h"
 
 
void
fib_prog_1(char *host, int n, int *arr)
{
    CLIENT *clnt;
    int  *result_1;
    input  fib_1_arg;
 
#ifndef DEBUG
    clnt = clnt_create (host, FIB_PROG, FIB_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif  /* DEBUG */
 
    int a[n];
    fib_1_arg.n = n;
    // fib_1_arg.arr = (int*)malloc(sizeof(int) * n);
 
    for(int i = 0; i < n; i++) {
        fib_1_arg.arr[i] = arr[i];
    }
 
    result_1 = fib_1(&fib_1_arg, clnt);
    if (result_1 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    } else {
        printf("Result: Max num is %d\n", *result_1);
    }
#ifndef DEBUG
    clnt_destroy (clnt);
#endif   /* DEBUG */
}
 
 
int
main (int argc, char *argv[])
{
    char *host;
 
    if (argc < 2) {
        printf ("usage: %s server_host\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    int n;
    printf("Enter number of elements: \n");
    int arr[100];
    scanf("%d",&n);
    printf("Enter numbers: \n");
    for(int i = 0; i < n; i++) {
        scanf("%d", &arr[i]);
    }
    fib_prog_1 (host,n,arr);
exit (0);
}
