/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 
#include "max.h"
 
int *
fib_1_svc(input *argp, struct svc_req *rqstp)
{
    static int  result;
 
    /*
     * insert server code here
     */
    int *arr = argp->arr;
    int n = argp->n;
    int mx = arr[0];
    printf("Server received data of %d integers\n", n);
    for(int i = 0; i < n; i++) {
        if(mx < arr[i]) mx = arr[i];
    }
    result = mx;
    return &result;
}
